import type { Metadata } from "next";
import { Inter, Onest } from "next/font/google";
import "./globals.css";
import { NavBar } from "@/components/nav-bar";
import { MainFooter } from "@/components/main-footer";

const mainFont = Onest({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={mainFont.className}>
        <NavBar />
        {children}
        <MainFooter />
      </body>
    </html>
  );
}
